build:gateway:
  stage: build
  image: data61/magda-builder-nodejs:0.0.38-0
  dependencies: 
  - prebuild:typescript-common
  script:
    - lerna bootstrap --scope=@magda/gateway 
    - lerna run build --scope=@magda/gateway
  artifacts:
    paths:
    - "node_modules"
    - "*/dist"
    - "*/node_modules"
    expire_in: 30 minutes