image: data61/magda-builder

variables:
  SBT_OPTS: >
    # 3gb heap
    -Xms3000M -Xmx3000M
    # unload classes we don't need
    -XX:+CMSClassUnloadingEnabled
    # aim for < 1000ms gc pauses (largely ignored)
    -XX:MaxGCPauseMillis=1000
    # use the next-gen collector that every blog on the internet says not to use because we know better than them
    -XX:+UseG1GC
    # use < 25% of time for GC
    -XX:GCTimeRatio=3
    # put the ivy cache in the workspace where gitlab can cache it
    -Dsbt.global.base=sbt-cache/sbtboot -Dsbt.boot.directory=sbt-cache/boot -Dsbt.ivy.home=sbt-cache/ivy
  CI: "true"

cache:
  paths:
  - "sbt-cache/ivy/cache"
  - "sbt-cache/boot"
  - "sbt-cache/sbtboot"
  - "sbt-cache/target"
  - "**/node_modules/"

test-node:
  script:
    - lerna bootstrap --scope=@magda/scripts 
    - npm run node-ci

test-scala:
  script:
    - sbt test

test-ui:
  script:
    - lerna --concurrency 2 --scope @magda/web-client --scope @magda/preview-map bootstrap
    - ./node_modules/.bin/eslint magda-web-client/src/
    - lerna --scope @magda/web-client --scope @magda/preview-map run build
    - lerna --scope @magda/preview-map --scope @magda/web-client run test