image: node

cache:
  paths:
  - node_modules/
  - magda-admin-api/node_modules/
  - magda-authorization-api/node_modules/
  - magda-ckan-connector/node_modules/
  - magda-csw-connector/node_modules/
  - magda-discussions-api/node_modules/
  - magda-feedback-api/node_modules/
  - magda-gateway/node_modules/
  - magda-project-open-data-connector/node_modules/
  - magda-sleuther-broken-link/node_modules/
  - magda-sleuther-format/node_modules/
  - magda-sleuther-framework/node_modules/
  - magda-sleuther-linked-data-rating/node_modules/
  - magda-sleuther-visualization/node_modules/
  - magda-typescript-common/node_modules/

before_script:
  - apt-get update -y  
  - apt-get install sbt -y
  - npm install -g lerna

build:
  script:
    - lerna bootstrap --scope=@magda/scripts 
    - npm run node-ci