dockerize:migrator-authorization-db:
  stage: dockerize
  image: data61/magda-builder-docker:0.0.38-0
  services:
  - docker:dind
  dependencies: []
  cache:
    paths: []
  script:
  - lerna bootstrap --scope=@magda/migrator-authorization-db
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker pull $CI_REGISTRY/magda-data/magda/data61/migrator-authorization-db:latest || true
  - lerna run docker-build-prod --scope=@magda/migrator-authorization-db -- -- --repository=$CI_REGISTRY/magda-data/magda --version=$CI_COMMIT_SHA --version=latest --cache-from=latest